# Generated by Django 4.1.7 on 2023-03-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('artist', models.CharField(max_length=250)),
                ('album', models.CharField(max_length=250)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('genre', models.CharField(max_length=250)),
                ('like', models.IntegerField(default=0)),
            ],
        ),
    ]
