# Generated by Django 4.1.7 on 2023-03-25 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_song_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 25, 0, 5, 41, 401245, tzinfo=datetime.timezone.utc)),
        ),
    ]
